<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;
use League\OAuth2\Client\Provider\FacebookUser;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Creating new user from FacebookUser data.
     *
     * @param FacebookUser $facebookUser
     * @return User
     */
    public function createNewFacebookUser(FacebookUser $facebookUser)
    {
        $user = new User();

        // Setting fields
        $user->setEmail($facebookUser->getEmail());
        $user->setFirstName($facebookUser->getFirstName());
        $user->setLastName($facebookUser->getLastName());
        $user->setFacebookId($facebookUser->getId());
        $user->setHasFacebookPicture(!$facebookUser->isDefaultPicture());

        // Saving user
        $this->getEntityManager()->persist($user);
        $this->getEntityManager()->flush();

        return $user;
    }
}
